### ISSUE TITLE
Documented that this is only for testing, or fix stale cache + filling up memory issues

### ISSUE THREAD

**Issue by andrerom** [php-cache/array-adapter#3]
By design this has a high risk of filling up memory, and causing stale data and corresponding issues in applications *(the longer application is running the higher risk that some other request/server/process has invalidated items cached here)*.

Same issue exists in Stash, where similar driver in lib is documented for unit test, but Bundle is exposing option for end users to enable "InMemory" cache without really documenting the issues it can cause. 

### Possible solutions
A. Clearly documented that this is for testing only, and never use in any doc or examples or bundles or bridges, other then for internal tests.

B. Aim to support in prod where people want performance at own risk, then somewhat fix the issues:
 - Add limit *(100?)* to avoid filling up memory, clear in first in first out order to recycle items over time
 - Add flag to getItem(s) where application developer can specify that stale data is allowed on a use case by use case basis, pass this argument to adapter and only return items from this array cache if application accepts stale data.

With B this adapter can be somewhat reliably be used with Chain adapter in front of adapter serving the real shared cache pool, at least assuming the developer using api knows his domain well enough to know when he can safely use stale data.

**Comment by prisis** [comment]
Im for A, the user should not use, a array cache in production!

**Comment by Nyholm** [comment]
I really like B. If you fetch an object from cache, about 40% of the time is spent in Redis. So if i do: 
```php
$pool->getItem('key');
$pool->getItem('key');
```
I do two round trips to Redis. If I could use a local memory cache in-front of Redis it would be awesome. The example gets even better when you use redis on a different server or a file system cache.

**Comment by aequasi** [comment]
I'm also for B. In-memory caches can be very helpful for long-running processes
